package com.sap.document.sap.soap.functions.mc_style;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 *
 *
 *
 * This class was generated by Apache CXF 2.6.8
 * 2015-03-25T01:58:22.706-04:00
 * Generated source version: 2.6.8
 *
 */
@WebService(targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", name = "zus_websrv_maintain_mat_url")
@XmlSeeAlso({ObjectFactory.class})
public interface ZusWebsrvMaintainMatUrl {

    @WebMethod(operationName = "ZusMmFmMaintainMatUrl", action = "urn:sap-com:document:sap:soap:functions:mc-style:zus_websrv_maintain_mat_url:ZusMmFmMaintainMatUrlRequest")
    @RequestWrapper(localName = "ZusMmFmMaintainMatUrl", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "com.sap.document.sap.soap.functions.mc_style.ZusMmFmMaintainMatUrl")
    @ResponseWrapper(localName = "ZusMmFmMaintainMatUrlResponse", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "com.sap.document.sap.soap.functions.mc_style.ZusMmFmMaintainMatUrlResponse")
    @WebResult(name = "OpReturn", targetNamespace = "")
    public com.sap.document.sap.soap.functions.mc_style.Bapiret2 zusMmFmMaintainMatUrl(
        @WebParam(name = "IpTAddMaterials", targetNamespace = "")
        com.sap.document.sap.soap.functions.mc_style.ZttymmMatnrList ipTAddMaterials,
        @WebParam(name = "IpTDeleteMaterials", targetNamespace = "")
        com.sap.document.sap.soap.functions.mc_style.ZttymmMatnrList ipTDeleteMaterials,
        @WebParam(name = "IpTitle", targetNamespace = "")
        java.lang.String ipTitle,
        @WebParam(name = "IpUrl", targetNamespace = "")
        java.lang.String ipUrl
    );
}
